// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Reason for the access.
public struct AccessReason: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Type of access justification.
  public var type: AccessReason.Type_ = AccessReason.Type_()

  /// More detail about certain reason types. See comments for each type above.
  public var detail: Swift.String = Swift.String()

  /// Initialize a new instance of `AccessReason`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AccessReason().with { $0.type = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Type of access justification.
  public enum Type_: Codable, Equatable, Sendable {
    /// Default value for proto, shouldn't be used.
    case unspecified
    /// Customer made a request or raised an issue that required the principal to
    /// access customer data. `detail` is of the form ("#####" is the issue ID):
    ///
    /// - "Feedback Report: #####"
    /// - "Case Number: #####"
    /// - "Case ID: #####"
    /// - "E-PIN Reference: #####"
    /// - "Google-#####"
    /// - "T-#####"
    case customerInitiatedSupport
    /// The principal accessed customer data in order to diagnose or resolve a
    /// suspected issue in services. Often this access is used to confirm that
    /// customers are not affected by a suspected service issue or to remediate a
    /// reversible system issue.
    case googleInitiatedService
    /// Google initiated service for security, fraud, abuse, or compliance
    /// purposes.
    case googleInitiatedReview
    /// The principal was compelled to access customer data in order to respond
    /// to a legal third party data request or process, including legal processes
    /// from customers themselves.
    case thirdPartyDataRequest
    /// The principal accessed customer data in order to diagnose or resolve a
    /// suspected issue in services or a known outage.
    case googleResponseToProductionAlert
    /// Similar to 'GOOGLE_INITIATED_SERVICE' or 'GOOGLE_INITIATED_REVIEW', but
    /// with universe agnostic naming. The principal accessed customer data in
    /// order to diagnose or resolve a suspected issue in services or a known
    /// outage, or for security, fraud, abuse, or compliance review purposes.
    case cloudInitiatedAccess
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .customerInitiatedSupport: return 1
      case .googleInitiatedService: return 2
      case .googleInitiatedReview: return 3
      case .thirdPartyDataRequest: return 4
      case .googleResponseToProductionAlert: return 5
      case .cloudInitiatedAccess: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TYPE_UNSPECIFIED"
      case .customerInitiatedSupport: return "CUSTOMER_INITIATED_SUPPORT"
      case .googleInitiatedService: return "GOOGLE_INITIATED_SERVICE"
      case .googleInitiatedReview: return "GOOGLE_INITIATED_REVIEW"
      case .thirdPartyDataRequest: return "THIRD_PARTY_DATA_REQUEST"
      case .googleResponseToProductionAlert: return "GOOGLE_RESPONSE_TO_PRODUCTION_ALERT"
      case .cloudInitiatedAccess: return "CLOUD_INITIATED_ACCESS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TYPE_UNSPECIFIED": self = .unspecified
      case "CUSTOMER_INITIATED_SUPPORT": self = .customerInitiatedSupport
      case "GOOGLE_INITIATED_SERVICE": self = .googleInitiatedService
      case "GOOGLE_INITIATED_REVIEW": self = .googleInitiatedReview
      case "THIRD_PARTY_DATA_REQUEST": self = .thirdPartyDataRequest
      case "GOOGLE_RESPONSE_TO_PRODUCTION_ALERT": self = .googleResponseToProductionAlert
      case "CLOUD_INITIATED_ACCESS": self = .cloudInitiatedAccess
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .customerInitiatedSupport
      case 2: self = .googleInitiatedService
      case 3: self = .googleInitiatedReview
      case 4: self = .thirdPartyDataRequest
      case 5: self = .googleResponseToProductionAlert
      case 6: self = .cloudInitiatedAccess
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .customerInitiatedSupport: return try container.encode(1)
      case .googleInitiatedService: return try container.encode(2)
      case .googleInitiatedReview: return try container.encode(3)
      case .thirdPartyDataRequest: return try container.encode(4)
      case .googleResponseToProductionAlert: return try container.encode(5)
      case .cloudInitiatedAccess: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudcontrolspartner.v1.AccessReason"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
