// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class CloudControlsPartnerMonitoringLogging: CloudControlsPartnerMonitoringStub {
    let inner: any CloudControlsPartnerMonitoringStub
    let logger: Logger

    public init(_ inner: any CloudControlsPartnerMonitoringStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-cloudcontrolspartner-v1"
      logger[metadataKey: "gcp.client.service"] = "cloudcontrolspartner"
      logger[metadataKey: "gcp.experimental.swift.client"] = "CloudControlsPartnerMonitoring"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listViolations(
      request: ListViolationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.ListViolationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listViolations",
        action: {
          (r: ListViolationsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudControlsPartnerV1.ListViolationsResponse
          in
          return try await self.inner.listViolations(request: r, options: o)
        })
    }

    public func getViolation(
      request: GetViolationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.Violation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getViolation",
        action: {
          (r: GetViolationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudControlsPartnerV1.Violation
          in
          return try await self.inner.getViolation(request: r, options: o)
        })
    }
  }
}
