// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class CloudControlsPartnerCoreLogging: CloudControlsPartnerCoreStub {
    let inner: any CloudControlsPartnerCoreStub
    let logger: Logger

    public init(_ inner: any CloudControlsPartnerCoreStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-cloudcontrolspartner-v1"
      logger[metadataKey: "gcp.client.service"] = "cloudcontrolspartner"
      logger[metadataKey: "gcp.experimental.swift.client"] = "CloudControlsPartnerCore"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func getWorkload(
      request: GetWorkloadRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.Workload {
      try await self._intercept(
        request: request,
        options: options,
        name: "getWorkload",
        action: {
          (r: GetWorkloadRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudControlsPartnerV1.Workload
          in
          return try await self.inner.getWorkload(request: r, options: o)
        })
    }

    public func listWorkloads(
      request: ListWorkloadsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.ListWorkloadsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listWorkloads",
        action: {
          (r: ListWorkloadsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudControlsPartnerV1.ListWorkloadsResponse
          in
          return try await self.inner.listWorkloads(request: r, options: o)
        })
    }

    public func getCustomer(
      request: GetCustomerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.Customer {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCustomer",
        action: {
          (r: GetCustomerRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudControlsPartnerV1.Customer
          in
          return try await self.inner.getCustomer(request: r, options: o)
        })
    }

    public func listCustomers(
      request: ListCustomersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.ListCustomersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listCustomers",
        action: {
          (r: ListCustomersRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudControlsPartnerV1.ListCustomersResponse
          in
          return try await self.inner.listCustomers(request: r, options: o)
        })
    }

    public func getEkmConnections(
      request: GetEkmConnectionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.EkmConnections {
      try await self._intercept(
        request: request,
        options: options,
        name: "getEkmConnections",
        action: {
          (r: GetEkmConnectionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudControlsPartnerV1.EkmConnections
          in
          return try await self.inner.getEkmConnections(request: r, options: o)
        })
    }

    public func getPartnerPermissions(
      request: GetPartnerPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.PartnerPermissions {
      try await self._intercept(
        request: request,
        options: options,
        name: "getPartnerPermissions",
        action: {
          (r: GetPartnerPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudControlsPartnerV1.PartnerPermissions
          in
          return try await self.inner.getPartnerPermissions(request: r, options: o)
        })
    }

    public func listAccessApprovalRequests(
      request: ListAccessApprovalRequestsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.ListAccessApprovalRequestsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listAccessApprovalRequests",
        action: {
          (r: ListAccessApprovalRequestsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudControlsPartnerV1.ListAccessApprovalRequestsResponse
          in
          return try await self.inner.listAccessApprovalRequests(request: r, options: o)
        })
    }

    public func getPartner(
      request: GetPartnerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.Partner {
      try await self._intercept(
        request: request,
        options: options,
        name: "getPartner",
        action: {
          (r: GetPartnerRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudControlsPartnerV1.Partner
          in
          return try await self.inner.getPartner(request: r, options: o)
        })
    }

    public func createCustomer(
      request: CreateCustomerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.Customer {
      try await self._intercept(
        request: request,
        options: options,
        name: "createCustomer",
        action: {
          (r: CreateCustomerRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudControlsPartnerV1.Customer
          in
          return try await self.inner.createCustomer(request: r, options: o)
        })
    }

    public func updateCustomer(
      request: UpdateCustomerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.Customer {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateCustomer",
        action: {
          (r: UpdateCustomerRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudControlsPartnerV1.Customer
          in
          return try await self.inner.updateCustomer(request: r, options: o)
        })
    }

    public func deleteCustomer(
      request: DeleteCustomerRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteCustomer",
        action: { (r: DeleteCustomerRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteCustomer(request: r, options: o)
        })
    }
  }
}
