// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  final class CloudControlsPartnerCoreRetry: CloudControlsPartnerCoreStub {
    let inner: any CloudControlsPartnerCoreStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any CloudControlsPartnerCoreStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func getWorkload(
      request: GetWorkloadRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.Workload {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetWorkloadRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudControlsPartnerV1.Workload
          in
          return try await self.inner.getWorkload(request: r, options: o)
        })
    }

    public func listWorkloads(
      request: ListWorkloadsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.ListWorkloadsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListWorkloadsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudControlsPartnerV1.ListWorkloadsResponse
          in
          return try await self.inner.listWorkloads(request: r, options: o)
        })
    }

    public func getCustomer(
      request: GetCustomerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.Customer {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetCustomerRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudControlsPartnerV1.Customer
          in
          return try await self.inner.getCustomer(request: r, options: o)
        })
    }

    public func listCustomers(
      request: ListCustomersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.ListCustomersResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListCustomersRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudControlsPartnerV1.ListCustomersResponse
          in
          return try await self.inner.listCustomers(request: r, options: o)
        })
    }

    public func getEkmConnections(
      request: GetEkmConnectionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.EkmConnections {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetEkmConnectionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudControlsPartnerV1.EkmConnections
          in
          return try await self.inner.getEkmConnections(request: r, options: o)
        })
    }

    public func getPartnerPermissions(
      request: GetPartnerPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.PartnerPermissions {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetPartnerPermissionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudControlsPartnerV1.PartnerPermissions
          in
          return try await self.inner.getPartnerPermissions(request: r, options: o)
        })
    }

    public func listAccessApprovalRequests(
      request: ListAccessApprovalRequestsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.ListAccessApprovalRequestsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListAccessApprovalRequestsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudControlsPartnerV1.ListAccessApprovalRequestsResponse
          in
          return try await self.inner.listAccessApprovalRequests(request: r, options: o)
        })
    }

    public func getPartner(
      request: GetPartnerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.Partner {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetPartnerRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudControlsPartnerV1.Partner
          in
          return try await self.inner.getPartner(request: r, options: o)
        })
    }

    public func createCustomer(
      request: CreateCustomerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.Customer {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateCustomerRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudControlsPartnerV1.Customer
          in
          return try await self.inner.createCustomer(request: r, options: o)
        })
    }

    public func updateCustomer(
      request: UpdateCustomerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.Customer {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateCustomerRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudControlsPartnerV1.Customer
          in
          return try await self.inner.updateCustomer(request: r, options: o)
        })
    }

    public func deleteCustomer(
      request: DeleteCustomerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteCustomerRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteCustomer(request: r, options: o)
        })
    }
  }
}
