// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleCloudGax

/// Service describing handlers for resources
///
/// @Snippet(path: "CloudControlsPartnerCoreQuickstart")
public final class CloudControlsPartnerCoreClient: Clients.CloudControlsPartnerCoreProtocol,
  Sendable
{
  let inner: any Clients.CloudControlsPartnerCoreStub

  /// Creates a new `CloudControlsPartnerCoreClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.CloudControlsPartnerCoreStub =
      try Clients.CloudControlsPartnerCoreTransport(options)
    inner = Clients.CloudControlsPartnerCoreRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.CloudControlsPartnerCoreLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Gets details of a single workload
  ///
  /// @Snippet(path: "CloudControlsPartnerCore_GetWorkload")
  public func getWorkload(
    request: GetWorkloadRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudControlsPartnerV1.Workload {
    try await self.inner.getWorkload(request: request, options: options)
  }

  /// Lists customer workloads for a given customer org id
  ///
  /// @Snippet(path: "CloudControlsPartnerCore_ListWorkloads")
  public func listWorkloads(
    request: ListWorkloadsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudControlsPartnerV1.ListWorkloadsResponse {
    try await self.inner.listWorkloads(request: request, options: options)
  }

  /// Lists customer workloads for a given customer org id
  ///
  /// @Snippet(path: "CloudControlsPartnerCore_ListWorkloads")
  public func listWorkloads(
    byItem: ListWorkloadsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Workload, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudControlsPartnerV1.ListWorkloadsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listWorkloads(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single customer
  ///
  /// @Snippet(path: "CloudControlsPartnerCore_GetCustomer")
  public func getCustomer(
    request: GetCustomerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudControlsPartnerV1.Customer {
    try await self.inner.getCustomer(request: request, options: options)
  }

  /// Lists customers of a partner identified by its Google Cloud organization ID
  ///
  /// @Snippet(path: "CloudControlsPartnerCore_ListCustomers")
  public func listCustomers(
    request: ListCustomersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudControlsPartnerV1.ListCustomersResponse {
    try await self.inner.listCustomers(request: request, options: options)
  }

  /// Lists customers of a partner identified by its Google Cloud organization ID
  ///
  /// @Snippet(path: "CloudControlsPartnerCore_ListCustomers")
  public func listCustomers(
    byItem: ListCustomersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Customer, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudControlsPartnerV1.ListCustomersResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listCustomers(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets the EKM connections associated with a workload
  ///
  /// @Snippet(path: "CloudControlsPartnerCore_GetEkmConnections")
  public func getEkmConnections(
    request: GetEkmConnectionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudControlsPartnerV1.EkmConnections {
    try await self.inner.getEkmConnections(request: request, options: options)
  }

  /// Gets the partner permissions granted for a workload
  ///
  /// @Snippet(path: "CloudControlsPartnerCore_GetPartnerPermissions")
  public func getPartnerPermissions(
    request: GetPartnerPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudControlsPartnerV1.PartnerPermissions {
    try await self.inner.getPartnerPermissions(request: request, options: options)
  }

  /// Deprecated: Only returns access approval requests directly associated with
  /// an assured workload folder.
  ///
  /// @Snippet(path: "CloudControlsPartnerCore_ListAccessApprovalRequests")
  @available(*, deprecated)
  public func listAccessApprovalRequests(
    request: ListAccessApprovalRequestsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudControlsPartnerV1.ListAccessApprovalRequestsResponse {
    try await self.inner.listAccessApprovalRequests(request: request, options: options)
  }

  /// Deprecated: Only returns access approval requests directly associated with
  /// an assured workload folder.
  ///
  /// @Snippet(path: "CloudControlsPartnerCore_ListAccessApprovalRequests")
  @available(*, deprecated)
  public func listAccessApprovalRequests(
    byItem: ListAccessApprovalRequestsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AccessApprovalRequest, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudControlsPartnerV1.ListAccessApprovalRequestsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listAccessApprovalRequests(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Get details of a Partner.
  ///
  /// @Snippet(path: "CloudControlsPartnerCore_GetPartner")
  public func getPartner(
    request: GetPartnerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudControlsPartnerV1.Partner {
    try await self.inner.getPartner(request: request, options: options)
  }

  /// Creates a new customer.
  ///
  /// @Snippet(path: "CloudControlsPartnerCore_CreateCustomer")
  public func createCustomer(
    request: CreateCustomerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudControlsPartnerV1.Customer {
    try await self.inner.createCustomer(request: request, options: options)
  }

  /// Update details of a single customer
  ///
  /// @Snippet(path: "CloudControlsPartnerCore_UpdateCustomer")
  public func updateCustomer(
    request: UpdateCustomerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudControlsPartnerV1.Customer {
    try await self.inner.updateCustomer(request: request, options: options)
  }

  /// Delete details of a single customer
  ///
  /// @Snippet(path: "CloudControlsPartnerCore_DeleteCustomer")
  public func deleteCustomer(
    request: DeleteCustomerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteCustomer(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `CloudControlsPartnerCoreClient`.
  ///
  /// To mock `CloudControlsPartnerCoreClient` change your functions to receive
  /// `some CloudControlsPartnerCoreProtocol` or `any CloudControlsPartnerCoreProtocol`
  /// and pass a mock implementation in your tests.
  public protocol CloudControlsPartnerCoreProtocol {
    /// See `CloudControlsPartnerCoreClient.getWorkload`.
    func getWorkload(request: GetWorkloadRequest) async throws
      -> GoogleCloudControlsPartnerV1.Workload

    /// See `CloudControlsPartnerCoreClient.getWorkload`.
    func getWorkload(
      name: Swift.String,
    ) async throws -> GoogleCloudControlsPartnerV1.Workload

    /// See `CloudControlsPartnerCoreClient.listWorkloads`.
    func listWorkloads(request: ListWorkloadsRequest) async throws
      -> GoogleCloudControlsPartnerV1.ListWorkloadsResponse

    /// See `CloudControlsPartnerCoreClient.listWorkloads`.
    func listWorkloads(
      byItem: ListWorkloadsRequest
    ) throws -> any AsyncSequence<Workload, Swift.Error>

    /// See `CloudControlsPartnerCoreClient.listWorkloads`.
    func listWorkloads(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Workload, Swift.Error>

    /// See `CloudControlsPartnerCoreClient.getCustomer`.
    func getCustomer(request: GetCustomerRequest) async throws
      -> GoogleCloudControlsPartnerV1.Customer

    /// See `CloudControlsPartnerCoreClient.getCustomer`.
    func getCustomer(
      name: Swift.String,
    ) async throws -> GoogleCloudControlsPartnerV1.Customer

    /// See `CloudControlsPartnerCoreClient.listCustomers`.
    func listCustomers(request: ListCustomersRequest) async throws
      -> GoogleCloudControlsPartnerV1.ListCustomersResponse

    /// See `CloudControlsPartnerCoreClient.listCustomers`.
    func listCustomers(
      byItem: ListCustomersRequest
    ) throws -> any AsyncSequence<Customer, Swift.Error>

    /// See `CloudControlsPartnerCoreClient.listCustomers`.
    func listCustomers(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Customer, Swift.Error>

    /// See `CloudControlsPartnerCoreClient.getEkmConnections`.
    func getEkmConnections(request: GetEkmConnectionsRequest) async throws
      -> GoogleCloudControlsPartnerV1.EkmConnections

    /// See `CloudControlsPartnerCoreClient.getEkmConnections`.
    func getEkmConnections(
      name: Swift.String,
    ) async throws -> GoogleCloudControlsPartnerV1.EkmConnections

    /// See `CloudControlsPartnerCoreClient.getPartnerPermissions`.
    func getPartnerPermissions(request: GetPartnerPermissionsRequest) async throws
      -> GoogleCloudControlsPartnerV1.PartnerPermissions

    /// See `CloudControlsPartnerCoreClient.getPartnerPermissions`.
    func getPartnerPermissions(
      name: Swift.String,
    ) async throws -> GoogleCloudControlsPartnerV1.PartnerPermissions

    /// See `CloudControlsPartnerCoreClient.listAccessApprovalRequests`.
    @available(*, deprecated)
    func listAccessApprovalRequests(request: ListAccessApprovalRequestsRequest) async throws
      -> GoogleCloudControlsPartnerV1.ListAccessApprovalRequestsResponse

    /// See `CloudControlsPartnerCoreClient.listAccessApprovalRequests`.
    @available(*, deprecated)
    func listAccessApprovalRequests(
      byItem: ListAccessApprovalRequestsRequest
    ) throws -> any AsyncSequence<AccessApprovalRequest, Swift.Error>

    /// See `CloudControlsPartnerCoreClient.listAccessApprovalRequests`.
    @available(*, deprecated)
    func listAccessApprovalRequests(
      parent: Swift.String,
    ) throws -> any AsyncSequence<AccessApprovalRequest, Swift.Error>

    /// See `CloudControlsPartnerCoreClient.getPartner`.
    func getPartner(request: GetPartnerRequest) async throws -> GoogleCloudControlsPartnerV1.Partner

    /// See `CloudControlsPartnerCoreClient.getPartner`.
    func getPartner(
      name: Swift.String,
    ) async throws -> GoogleCloudControlsPartnerV1.Partner

    /// See `CloudControlsPartnerCoreClient.createCustomer`.
    func createCustomer(request: CreateCustomerRequest) async throws
      -> GoogleCloudControlsPartnerV1.Customer

    /// See `CloudControlsPartnerCoreClient.createCustomer`.
    func createCustomer(
      parent: Swift.String,
      customer: Customer?,
      customerId: Swift.String,
    ) async throws -> GoogleCloudControlsPartnerV1.Customer

    /// See `CloudControlsPartnerCoreClient.updateCustomer`.
    func updateCustomer(request: UpdateCustomerRequest) async throws
      -> GoogleCloudControlsPartnerV1.Customer

    /// See `CloudControlsPartnerCoreClient.updateCustomer`.
    func updateCustomer(
      customer: Customer?,
      updateMask: GoogleCloudWKT.FieldMask?,
    ) async throws -> GoogleCloudControlsPartnerV1.Customer

    /// See `CloudControlsPartnerCoreClient.deleteCustomer`.
    func deleteCustomer(request: DeleteCustomerRequest) async throws

    /// See `CloudControlsPartnerCoreClient.deleteCustomer`.
    func deleteCustomer(
      name: Swift.String,
    ) async throws

    /// See `CloudControlsPartnerCoreClient.getWorkload`.
    func getWorkload(
      request: GetWorkloadRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.Workload

    /// See `CloudControlsPartnerCoreClient.listWorkloads`.
    func listWorkloads(
      request: ListWorkloadsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.ListWorkloadsResponse

    /// See `CloudControlsPartnerCoreClient.listWorkloads`.
    func listWorkloads(
      byItem: ListWorkloadsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Workload, Swift.Error>

    /// See `CloudControlsPartnerCoreClient.getCustomer`.
    func getCustomer(
      request: GetCustomerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.Customer

    /// See `CloudControlsPartnerCoreClient.listCustomers`.
    func listCustomers(
      request: ListCustomersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.ListCustomersResponse

    /// See `CloudControlsPartnerCoreClient.listCustomers`.
    func listCustomers(
      byItem: ListCustomersRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Customer, Swift.Error>

    /// See `CloudControlsPartnerCoreClient.getEkmConnections`.
    func getEkmConnections(
      request: GetEkmConnectionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.EkmConnections

    /// See `CloudControlsPartnerCoreClient.getPartnerPermissions`.
    func getPartnerPermissions(
      request: GetPartnerPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.PartnerPermissions

    /// See `CloudControlsPartnerCoreClient.listAccessApprovalRequests`.
    @available(*, deprecated)
    func listAccessApprovalRequests(
      request: ListAccessApprovalRequestsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.ListAccessApprovalRequestsResponse

    /// See `CloudControlsPartnerCoreClient.listAccessApprovalRequests`.
    @available(*, deprecated)
    func listAccessApprovalRequests(
      byItem: ListAccessApprovalRequestsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<AccessApprovalRequest, Swift.Error>

    /// See `CloudControlsPartnerCoreClient.getPartner`.
    func getPartner(
      request: GetPartnerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.Partner

    /// See `CloudControlsPartnerCoreClient.createCustomer`.
    func createCustomer(
      request: CreateCustomerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.Customer

    /// See `CloudControlsPartnerCoreClient.updateCustomer`.
    func updateCustomer(
      request: UpdateCustomerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.Customer

    /// See `CloudControlsPartnerCoreClient.deleteCustomer`.
    func deleteCustomer(
      request: DeleteCustomerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.CloudControlsPartnerCoreProtocol {
  public func getWorkload(request: GetWorkloadRequest) async throws
    -> GoogleCloudControlsPartnerV1.Workload
  {
    try await self.getWorkload(request: request, options: .init())
  }

  public func getWorkload(
    request: GetWorkloadRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudControlsPartnerV1.Workload {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getWorkload(
    name: Swift.String,
  ) async throws -> GoogleCloudControlsPartnerV1.Workload {
    let request = GetWorkloadRequest().with {
      $0.name = name
    }
    return try await self.getWorkload(request: request)
  }

  public func listWorkloads(request: ListWorkloadsRequest) async throws
    -> GoogleCloudControlsPartnerV1.ListWorkloadsResponse
  {
    try await self.listWorkloads(request: request, options: .init())
  }

  public func listWorkloads(
    request: ListWorkloadsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudControlsPartnerV1.ListWorkloadsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listWorkloads(
    byItem: ListWorkloadsRequest
  ) throws -> any AsyncSequence<Workload, Swift.Error> {
    try self.listWorkloads(byItem: byItem, options: .init())
  }

  public func listWorkloads(
    byItem: ListWorkloadsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Workload, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudControlsPartnerV1.ListWorkloadsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listWorkloads(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Workload, Swift.Error> {
    let request = ListWorkloadsRequest().with {
      $0.parent = parent
    }
    return try self.listWorkloads(byItem: request)
  }

  public func getCustomer(request: GetCustomerRequest) async throws
    -> GoogleCloudControlsPartnerV1.Customer
  {
    try await self.getCustomer(request: request, options: .init())
  }

  public func getCustomer(
    request: GetCustomerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudControlsPartnerV1.Customer {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getCustomer(
    name: Swift.String,
  ) async throws -> GoogleCloudControlsPartnerV1.Customer {
    let request = GetCustomerRequest().with {
      $0.name = name
    }
    return try await self.getCustomer(request: request)
  }

  public func listCustomers(request: ListCustomersRequest) async throws
    -> GoogleCloudControlsPartnerV1.ListCustomersResponse
  {
    try await self.listCustomers(request: request, options: .init())
  }

  public func listCustomers(
    request: ListCustomersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudControlsPartnerV1.ListCustomersResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listCustomers(
    byItem: ListCustomersRequest
  ) throws -> any AsyncSequence<Customer, Swift.Error> {
    try self.listCustomers(byItem: byItem, options: .init())
  }

  public func listCustomers(
    byItem: ListCustomersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Customer, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudControlsPartnerV1.ListCustomersResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listCustomers(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Customer, Swift.Error> {
    let request = ListCustomersRequest().with {
      $0.parent = parent
    }
    return try self.listCustomers(byItem: request)
  }

  public func getEkmConnections(request: GetEkmConnectionsRequest) async throws
    -> GoogleCloudControlsPartnerV1.EkmConnections
  {
    try await self.getEkmConnections(request: request, options: .init())
  }

  public func getEkmConnections(
    request: GetEkmConnectionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudControlsPartnerV1.EkmConnections {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getEkmConnections(
    name: Swift.String,
  ) async throws -> GoogleCloudControlsPartnerV1.EkmConnections {
    let request = GetEkmConnectionsRequest().with {
      $0.name = name
    }
    return try await self.getEkmConnections(request: request)
  }

  public func getPartnerPermissions(request: GetPartnerPermissionsRequest) async throws
    -> GoogleCloudControlsPartnerV1.PartnerPermissions
  {
    try await self.getPartnerPermissions(request: request, options: .init())
  }

  public func getPartnerPermissions(
    request: GetPartnerPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudControlsPartnerV1.PartnerPermissions {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getPartnerPermissions(
    name: Swift.String,
  ) async throws -> GoogleCloudControlsPartnerV1.PartnerPermissions {
    let request = GetPartnerPermissionsRequest().with {
      $0.name = name
    }
    return try await self.getPartnerPermissions(request: request)
  }

  public func listAccessApprovalRequests(request: ListAccessApprovalRequestsRequest) async throws
    -> GoogleCloudControlsPartnerV1.ListAccessApprovalRequestsResponse
  {
    try await self.listAccessApprovalRequests(request: request, options: .init())
  }

  public func listAccessApprovalRequests(
    request: ListAccessApprovalRequestsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudControlsPartnerV1.ListAccessApprovalRequestsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listAccessApprovalRequests(
    byItem: ListAccessApprovalRequestsRequest
  ) throws -> any AsyncSequence<AccessApprovalRequest, Swift.Error> {
    try self.listAccessApprovalRequests(byItem: byItem, options: .init())
  }

  public func listAccessApprovalRequests(
    byItem: ListAccessApprovalRequestsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AccessApprovalRequest, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudControlsPartnerV1.ListAccessApprovalRequestsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAccessApprovalRequests(
    parent: Swift.String,
  ) throws -> any AsyncSequence<AccessApprovalRequest, Swift.Error> {
    let request = ListAccessApprovalRequestsRequest().with {
      $0.parent = parent
    }
    return try self.listAccessApprovalRequests(byItem: request)
  }

  public func getPartner(request: GetPartnerRequest) async throws
    -> GoogleCloudControlsPartnerV1.Partner
  {
    try await self.getPartner(request: request, options: .init())
  }

  public func getPartner(
    request: GetPartnerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudControlsPartnerV1.Partner {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getPartner(
    name: Swift.String,
  ) async throws -> GoogleCloudControlsPartnerV1.Partner {
    let request = GetPartnerRequest().with {
      $0.name = name
    }
    return try await self.getPartner(request: request)
  }

  public func createCustomer(request: CreateCustomerRequest) async throws
    -> GoogleCloudControlsPartnerV1.Customer
  {
    try await self.createCustomer(request: request, options: .init())
  }

  public func createCustomer(
    request: CreateCustomerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudControlsPartnerV1.Customer {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createCustomer(
    parent: Swift.String,
    customer: Customer?,
    customerId: Swift.String,
  ) async throws -> GoogleCloudControlsPartnerV1.Customer {
    let request = CreateCustomerRequest().with {
      $0.parent = parent
      $0.customer = customer
      $0.customerId = customerId
    }
    return try await self.createCustomer(request: request)
  }

  public func updateCustomer(request: UpdateCustomerRequest) async throws
    -> GoogleCloudControlsPartnerV1.Customer
  {
    try await self.updateCustomer(request: request, options: .init())
  }

  public func updateCustomer(
    request: UpdateCustomerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudControlsPartnerV1.Customer {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateCustomer(
    customer: Customer?,
    updateMask: GoogleCloudWKT.FieldMask?,
  ) async throws -> GoogleCloudControlsPartnerV1.Customer {
    let request = UpdateCustomerRequest().with {
      $0.customer = customer
      $0.updateMask = updateMask
    }
    return try await self.updateCustomer(request: request)
  }

  public func deleteCustomer(request: DeleteCustomerRequest) async throws {
    try await self.deleteCustomer(request: request, options: .init())
  }

  public func deleteCustomer(
    request: DeleteCustomerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteCustomer(
    name: Swift.String,
  ) async throws {
    let request = DeleteCustomerRequest().with {
      $0.name = name
    }
    try await self.deleteCustomer(request: request)
  }
}
