// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleWKT
import GoogleGax

extension Clients {
  protocol CloudControlsPartnerCoreStub: Sendable {
    func getWorkload(
      request: GetWorkloadRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.Workload

    func listWorkloads(
      request: ListWorkloadsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.ListWorkloadsResponse

    func getCustomer(
      request: GetCustomerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.Customer

    func listCustomers(
      request: ListCustomersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.ListCustomersResponse

    func getEkmConnections(
      request: GetEkmConnectionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.EkmConnections

    func getPartnerPermissions(
      request: GetPartnerPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.PartnerPermissions

    func listAccessApprovalRequests(
      request: ListAccessApprovalRequestsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.ListAccessApprovalRequestsResponse

    func getPartner(
      request: GetPartnerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.Partner

    func createCustomer(
      request: CreateCustomerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.Customer

    func updateCustomer(
      request: UpdateCustomerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudControlsPartnerV1.Customer

    func deleteCustomer(
      request: DeleteCustomerRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
