// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Details about the EKM connection
public struct EkmConnection: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Resource name of the EKM connection in the format:
  /// projects/{project}/locations/{location}/ekmConnections/{ekm_connection}
  public var connectionName: Swift.String = Swift.String()

  /// Output only. The connection state
  public var connectionState: EkmConnection.ConnectionState = EkmConnection.ConnectionState()

  /// The connection error that occurred if any
  public var connectionError: EkmConnection.ConnectionError? = nil

  /// Initialize a new instance of `EkmConnection`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EkmConnection().with { $0.connectionName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Information around the error that occurred if the connection state is
  /// anything other than available or unspecified
  public struct ConnectionError: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The error domain for the error
    public var errorDomain: Swift.String = Swift.String()

    /// The error message for the error
    public var errorMessage: Swift.String = Swift.String()

    /// Initialize a new instance of `ConnectionError`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ConnectionError().with { $0.errorDomain = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.cloudcontrolspartner.v1.EkmConnection.ConnectionError"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The EKM connection state.
  public enum ConnectionState: Codable, Equatable, Sendable {
    /// Unspecified EKM connection state
    case unspecified
    /// Available EKM connection state
    case available
    /// Not available EKM connection state
    case notAvailable
    /// Error EKM connection state
    case error
    /// Permission denied EKM connection state
    case permissionDenied
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .available: return 1
      case .notAvailable: return 2
      case .error: return 3
      case .permissionDenied: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CONNECTION_STATE_UNSPECIFIED"
      case .available: return "AVAILABLE"
      case .notAvailable: return "NOT_AVAILABLE"
      case .error: return "ERROR"
      case .permissionDenied: return "PERMISSION_DENIED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ConnectionState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CONNECTION_STATE_UNSPECIFIED": self = .unspecified
      case "AVAILABLE": self = .available
      case "NOT_AVAILABLE": self = .notAvailable
      case "ERROR": self = .error
      case "PERMISSION_DENIED": self = .permissionDenied
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ConnectionState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .available
      case 2: self = .notAvailable
      case 3: self = .error
      case 4: self = .permissionDenied
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .available: return try container.encode(1)
      case .notAvailable: return try container.encode(2)
      case .error: return try container.encode(3)
      case .permissionDenied: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudcontrolspartner.v1.EkmConnection"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
