// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Holds information needed by Mudbray to use partner EKMs for workloads.
public struct EkmMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The Cloud EKM partner.
  public var ekmSolution: EkmMetadata.EkmSolution = EkmMetadata.EkmSolution()

  /// Endpoint for sending requests to the EKM for key provisioning during
  /// Assured Workload creation.
  public var ekmEndpointUri: Swift.String = Swift.String()

  /// Initialize a new instance of `EkmMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EkmMetadata().with { $0.ekmSolution = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Represents Google Cloud supported external key management partners
  /// [Google Cloud EKM partners
  /// docs](https://cloud.google.com/kms/docs/ekm#supported_partners).
  public enum EkmSolution: Codable, Equatable, Sendable {
    /// Unspecified EKM solution
    case unspecified
    /// EKM Partner Fortanix
    case fortanix
    /// EKM Partner FutureX
    case futurex
    /// EKM Partner Thales
    case thales
    /// This enum value is never used.
    @available(*, deprecated)
    case virtru
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .fortanix: return 1
      case .futurex: return 2
      case .thales: return 3
      case .virtru: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "EKM_SOLUTION_UNSPECIFIED"
      case .fortanix: return "FORTANIX"
      case .futurex: return "FUTUREX"
      case .thales: return "THALES"
      case .virtru: return "VIRTRU"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:EkmSolution/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "EKM_SOLUTION_UNSPECIFIED": self = .unspecified
      case "FORTANIX": self = .fortanix
      case "FUTUREX": self = .futurex
      case "THALES": self = .thales
      case "VIRTRU": self = .virtru
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:EkmSolution/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .fortanix
      case 2: self = .futurex
      case 3: self = .thales
      case 4: self = .virtru
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .fortanix: return try container.encode(1)
      case .futurex: return try container.encode(2)
      case .thales: return try container.encode(3)
      case .virtru: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudcontrolspartner.v1.EkmMetadata"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
