// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleType

/// Message for requesting list of Violations
public struct ListViolationsRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Parent resource
  /// Format
  /// `organizations/{organization}/locations/{location}/customers/{customer}/workloads/{workload}`
  public var parent: Swift.String = Swift.String()

  /// Optional. The maximum number of customers row to return. The service may
  /// return fewer than this value. If unspecified, at most 10 customers will be
  /// returned.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A page token, received from a previous `ListViolations` call.
  /// Provide this to retrieve the subsequent page.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. Filtering results
  public var filter: Swift.String = Swift.String()

  /// Optional. Hint for how to order the results
  public var orderBy: Swift.String = Swift.String()

  /// Optional. Specifies the interval for retrieving violations.
  /// if unspecified, all violations will be returned.
  public var interval: GoogleType.Interval? = nil

  /// Initialize a new instance of `ListViolationsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListViolationsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudcontrolspartner.v1.ListViolationsRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
