// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The permissions granted to the partner for a workload
public struct PartnerPermissions: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. Format:
  /// `organizations/{organization}/locations/{location}/customers/{customer}/workloads/{workload}/partnerPermissions`
  public var name: Swift.String = Swift.String()

  /// The partner permissions granted for the workload
  public var partnerPermissions: [PartnerPermissions.Permission] = []

  /// Initialize a new instance of `PartnerPermissions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PartnerPermissions().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public enum Permission: Codable, Equatable, Sendable {
    /// Unspecified partner permission
    case unspecified
    /// Permission for Access Transparency and emergency logs
    case accessTransparencyAndEmergencyAccessLogs
    /// Permission for Assured Workloads monitoring violations
    case assuredWorkloadsMonitoring
    /// Permission for Access Approval requests
    case accessApprovalRequests
    /// Permission for External Key Manager connection status
    case assuredWorkloadsEkmConnectionStatus
    /// Permission for support case details for Access Transparency log entries
    case accessTransparencyLogsSupportCaseViewer
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .accessTransparencyAndEmergencyAccessLogs: return 1
      case .assuredWorkloadsMonitoring: return 2
      case .accessApprovalRequests: return 3
      case .assuredWorkloadsEkmConnectionStatus: return 4
      case .accessTransparencyLogsSupportCaseViewer: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PERMISSION_UNSPECIFIED"
      case .accessTransparencyAndEmergencyAccessLogs:
        return "ACCESS_TRANSPARENCY_AND_EMERGENCY_ACCESS_LOGS"
      case .assuredWorkloadsMonitoring: return "ASSURED_WORKLOADS_MONITORING"
      case .accessApprovalRequests: return "ACCESS_APPROVAL_REQUESTS"
      case .assuredWorkloadsEkmConnectionStatus: return "ASSURED_WORKLOADS_EKM_CONNECTION_STATUS"
      case .accessTransparencyLogsSupportCaseViewer:
        return "ACCESS_TRANSPARENCY_LOGS_SUPPORT_CASE_VIEWER"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Permission/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PERMISSION_UNSPECIFIED": self = .unspecified
      case "ACCESS_TRANSPARENCY_AND_EMERGENCY_ACCESS_LOGS":
        self = .accessTransparencyAndEmergencyAccessLogs
      case "ASSURED_WORKLOADS_MONITORING": self = .assuredWorkloadsMonitoring
      case "ACCESS_APPROVAL_REQUESTS": self = .accessApprovalRequests
      case "ASSURED_WORKLOADS_EKM_CONNECTION_STATUS": self = .assuredWorkloadsEkmConnectionStatus
      case "ACCESS_TRANSPARENCY_LOGS_SUPPORT_CASE_VIEWER":
        self = .accessTransparencyLogsSupportCaseViewer
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Permission/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .accessTransparencyAndEmergencyAccessLogs
      case 2: self = .assuredWorkloadsMonitoring
      case 3: self = .accessApprovalRequests
      case 4: self = .assuredWorkloadsEkmConnectionStatus
      case 5: self = .accessTransparencyLogsSupportCaseViewer
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .accessTransparencyAndEmergencyAccessLogs: return try container.encode(1)
      case .assuredWorkloadsMonitoring: return try container.encode(2)
      case .accessApprovalRequests: return try container.encode(3)
      case .assuredWorkloadsEkmConnectionStatus: return try container.encode(4)
      case .accessTransparencyLogsSupportCaseViewer: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudcontrolspartner.v1.PartnerPermissions"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
