// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Details of resource Violation
public struct Violation: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. Format:
  /// `organizations/{organization}/locations/{location}/customers/{customer}/workloads/{workload}/violations/{violation}`
  public var name: Swift.String = Swift.String()

  /// Output only. Description for the Violation.
  /// e.g. OrgPolicy gcp.resourceLocations has non compliant value.
  public var description: Swift.String = Swift.String()

  /// Output only. Time of the event which triggered the Violation.
  public var beginTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The last time when the Violation record was updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Time of the event which fixed the Violation.
  /// If the violation is ACTIVE this will be empty.
  public var resolveTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Category under which this violation is mapped.
  /// e.g. Location, Service Usage, Access, Encryption, etc.
  public var category: Swift.String = Swift.String()

  /// Output only. State of the violation
  public var state: Violation.State = Violation.State()

  /// Output only. Immutable. Name of the OrgPolicy which was modified with
  /// non-compliant change and resulted this violation. Format:
  ///  `projects/{project_number}/policies/{constraint_name}`
  ///  `folders/{folder_id}/policies/{constraint_name}`
  ///  `organizations/{organization_id}/policies/{constraint_name}`
  public var nonCompliantOrgPolicy: Swift.String = Swift.String()

  /// The folder_id of the violation
  public var folderId: Swift.Int64 = Swift.Int64()

  /// Output only. Compliance violation remediation
  public var remediation: Violation.Remediation? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `Violation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Violation().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let description = CodingKeys(stringValue: "description")
    static let beginTime = CodingKeys(stringValue: "beginTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let resolveTime = CodingKeys(stringValue: "resolveTime")
    static let category = CodingKeys(stringValue: "category")
    static let state = CodingKeys(stringValue: "state")
    static let nonCompliantOrgPolicy = CodingKeys(stringValue: "nonCompliantOrgPolicy")
    static let folderId = CodingKeys(stringValue: "folderId")
    static let remediation = CodingKeys(stringValue: "remediation")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "description",
      "beginTime",
      "updateTime",
      "resolveTime",
      "category",
      "state",
      "nonCompliantOrgPolicy",
      "folderId",
      "remediation",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.beginTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .beginTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .updateTime)
    self.resolveTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .resolveTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .category) {
      self.category = value
    }
    if let value = try container.decodeIfPresent(Violation.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nonCompliantOrgPolicy)
    {
      self.nonCompliantOrgPolicy = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .folderId) {
      self.folderId = value
    }
    self.remediation = try container.decodeIfPresent(
      Violation.Remediation.self, forKey: .remediation)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.beginTime, forKey: .beginTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.resolveTime, forKey: .resolveTime)
    try container.encode(self.category, forKey: .category)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.nonCompliantOrgPolicy, forKey: .nonCompliantOrgPolicy)
    try container.encode(self.folderId, forKey: .folderId)
    try container.encodeIfPresent(self.remediation, forKey: .remediation)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Represents remediation guidance to resolve compliance violation for
  /// AssuredWorkload
  public struct Remediation: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. Remediation instructions to resolve violations
    public var instructions: Violation.Remediation.Instructions? = nil

    /// Values that can resolve the violation
    /// For example: for list org policy violations, this will either be the list
    /// of allowed or denied values
    public var compliantValues: [Swift.String] = []

    /// Output only. Remediation type based on the type of org policy values
    /// violated
    public var remediationType: Violation.Remediation.RemediationType = Violation.Remediation
      .RemediationType()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `Remediation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Remediation().with { $0.instructions = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let instructions = CodingKeys(stringValue: "instructions")
      static let compliantValues = CodingKeys(stringValue: "compliantValues")
      static let remediationType = CodingKeys(stringValue: "remediationType")

      static let _knownKeys: Set<Swift.String> = [
        "instructions",
        "compliantValues",
        "remediationType",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.instructions = try container.decodeIfPresent(
        Violation.Remediation.Instructions.self, forKey: .instructions)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .compliantValues) {
        self.compliantValues = value
      }
      if let value = try container.decodeIfPresent(
        Violation.Remediation.RemediationType.self, forKey: .remediationType)
      {
        self.remediationType = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.instructions, forKey: .instructions)
      try container.encode(self.compliantValues, forKey: .compliantValues)
      try container.encode(self.remediationType, forKey: .remediationType)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Instructions to remediate violation
    public struct Instructions: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Remediation instructions to resolve violation via gcloud cli
      public var gcloudInstructions: Violation.Remediation.Instructions.Gcloud? = nil

      /// Remediation instructions to resolve violation via cloud console
      public var consoleInstructions: Violation.Remediation.Instructions.Console? = nil

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

      /// Initialize a new instance of `Instructions`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Instructions().with { $0.gcloudInstructions = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let gcloudInstructions = CodingKeys(stringValue: "gcloudInstructions")
        static let consoleInstructions = CodingKeys(stringValue: "consoleInstructions")

        static let _knownKeys: Set<Swift.String> = [
          "gcloudInstructions",
          "consoleInstructions",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.gcloudInstructions = try container.decodeIfPresent(
          Violation.Remediation.Instructions.Gcloud.self, forKey: .gcloudInstructions)
        self.consoleInstructions = try container.decodeIfPresent(
          Violation.Remediation.Instructions.Console.self, forKey: .consoleInstructions)
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleCloudWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.gcloudInstructions, forKey: .gcloudInstructions)
        try container.encodeIfPresent(self.consoleInstructions, forKey: .consoleInstructions)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      /// Remediation instructions to resolve violation via gcloud cli
      public struct Gcloud: Codable, Equatable, GoogleCloudWKT._AnyPackable,
        Sendable
      {
        /// Gcloud command to resolve violation
        public var gcloudCommands: [Swift.String] = []

        /// Steps to resolve violation via gcloud cli
        public var steps: [Swift.String] = []

        /// Additional urls for more information about steps
        public var additionalLinks: [Swift.String] = []

        @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields =
          .init()

        /// Initialize a new instance of `Gcloud`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = Gcloud().with { $0.gcloudCommands = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        private struct CodingKeys: CodingKey {
          var stringValue: Swift.String
          var intValue: Swift.Int? { nil }
          init(stringValue: Swift.String) { self.stringValue = stringValue }
          init?(intValue: Swift.Int) { nil }

          static let gcloudCommands = CodingKeys(stringValue: "gcloudCommands")
          static let steps = CodingKeys(stringValue: "steps")
          static let additionalLinks = CodingKeys(stringValue: "additionalLinks")

          static let _knownKeys: Set<Swift.String> = [
            "gcloudCommands",
            "steps",
            "additionalLinks",
          ]
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.container(keyedBy: CodingKeys.self)
          if let value = try container.decodeIfPresent([Swift.String].self, forKey: .gcloudCommands)
          {
            self.gcloudCommands = value
          }
          if let value = try container.decodeIfPresent([Swift.String].self, forKey: .steps) {
            self.steps = value
          }
          if let value = try container.decodeIfPresent(
            [Swift.String].self, forKey: .additionalLinks)
          {
            self.additionalLinks = value
          }
          for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
            self._unknownFields.json[key.stringValue] = try container.decode(
              GoogleCloudWKT.Value.self, forKey: key)
          }
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.container(keyedBy: CodingKeys.self)
          try container.encode(self.gcloudCommands, forKey: .gcloudCommands)
          try container.encode(self.steps, forKey: .steps)
          try container.encode(self.additionalLinks, forKey: .additionalLinks)
          for (key, value) in self._unknownFields.json {
            try container.encode(value, forKey: CodingKeys(stringValue: key))
          }
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.cloudcontrolspartner.v1.Violation.Remediation.Instructions.Gcloud"
        }
        public init(fromAny any: GoogleCloudWKT.`Any`) throws {
          self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWKT.Struct {
          return try GoogleCloudWKT._slowAnySerialize(message: self)
        }
      }

      /// Remediation instructions to resolve violation via cloud console
      public struct Console: Codable, Equatable, GoogleCloudWKT._AnyPackable,
        Sendable
      {
        /// Link to console page where violations can be resolved
        public var consoleUris: [Swift.String] = []

        /// Steps to resolve violation via cloud console
        public var steps: [Swift.String] = []

        /// Additional urls for more information about steps
        public var additionalLinks: [Swift.String] = []

        @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields =
          .init()

        /// Initialize a new instance of `Console`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = Console().with { $0.consoleUris = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        private struct CodingKeys: CodingKey {
          var stringValue: Swift.String
          var intValue: Swift.Int? { nil }
          init(stringValue: Swift.String) { self.stringValue = stringValue }
          init?(intValue: Swift.Int) { nil }

          static let consoleUris = CodingKeys(stringValue: "consoleUris")
          static let steps = CodingKeys(stringValue: "steps")
          static let additionalLinks = CodingKeys(stringValue: "additionalLinks")

          static let _knownKeys: Set<Swift.String> = [
            "consoleUris",
            "steps",
            "additionalLinks",
          ]
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.container(keyedBy: CodingKeys.self)
          if let value = try container.decodeIfPresent([Swift.String].self, forKey: .consoleUris) {
            self.consoleUris = value
          }
          if let value = try container.decodeIfPresent([Swift.String].self, forKey: .steps) {
            self.steps = value
          }
          if let value = try container.decodeIfPresent(
            [Swift.String].self, forKey: .additionalLinks)
          {
            self.additionalLinks = value
          }
          for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
            self._unknownFields.json[key.stringValue] = try container.decode(
              GoogleCloudWKT.Value.self, forKey: key)
          }
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.container(keyedBy: CodingKeys.self)
          try container.encode(self.consoleUris, forKey: .consoleUris)
          try container.encode(self.steps, forKey: .steps)
          try container.encode(self.additionalLinks, forKey: .additionalLinks)
          for (key, value) in self._unknownFields.json {
            try container.encode(value, forKey: CodingKeys(stringValue: key))
          }
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.cloudcontrolspartner.v1.Violation.Remediation.Instructions.Console"
        }
        public init(fromAny any: GoogleCloudWKT.`Any`) throws {
          self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWKT.Struct {
          return try GoogleCloudWKT._slowAnySerialize(message: self)
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.cloudcontrolspartner.v1.Violation.Remediation.Instructions"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    /// Classifying remediation into various types based on the kind of
    /// violation. For example, violations caused due to changes in boolean org
    /// policy requires different remediation instructions compared to violation
    /// caused due to changes in allowed values of list org policy.
    public enum RemediationType: Codable, Equatable, Sendable {
      /// Unspecified remediation type
      case unspecified
      /// Remediation type for boolean org policy
      case remediationBooleanOrgPolicyViolation
      /// Remediation type for list org policy which have allowed values in the
      /// monitoring rule
      case remediationListAllowedValuesOrgPolicyViolation
      /// Remediation type for list org policy which have denied values in the
      /// monitoring rule
      case remediationListDeniedValuesOrgPolicyViolation
      /// Remediation type for gcp.restrictCmekCryptoKeyProjects
      case remediationRestrictCmekCryptoKeyProjectsOrgPolicyViolation
      /// Remediation type for resource violation.
      case remediationResourceViolation
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .remediationBooleanOrgPolicyViolation: return 1
        case .remediationListAllowedValuesOrgPolicyViolation: return 2
        case .remediationListDeniedValuesOrgPolicyViolation: return 3
        case .remediationRestrictCmekCryptoKeyProjectsOrgPolicyViolation: return 4
        case .remediationResourceViolation: return 5
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "REMEDIATION_TYPE_UNSPECIFIED"
        case .remediationBooleanOrgPolicyViolation:
          return "REMEDIATION_BOOLEAN_ORG_POLICY_VIOLATION"
        case .remediationListAllowedValuesOrgPolicyViolation:
          return "REMEDIATION_LIST_ALLOWED_VALUES_ORG_POLICY_VIOLATION"
        case .remediationListDeniedValuesOrgPolicyViolation:
          return "REMEDIATION_LIST_DENIED_VALUES_ORG_POLICY_VIOLATION"
        case .remediationRestrictCmekCryptoKeyProjectsOrgPolicyViolation:
          return "REMEDIATION_RESTRICT_CMEK_CRYPTO_KEY_PROJECTS_ORG_POLICY_VIOLATION"
        case .remediationResourceViolation: return "REMEDIATION_RESOURCE_VIOLATION"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RemediationType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "REMEDIATION_TYPE_UNSPECIFIED": self = .unspecified
        case "REMEDIATION_BOOLEAN_ORG_POLICY_VIOLATION":
          self = .remediationBooleanOrgPolicyViolation
        case "REMEDIATION_LIST_ALLOWED_VALUES_ORG_POLICY_VIOLATION":
          self = .remediationListAllowedValuesOrgPolicyViolation
        case "REMEDIATION_LIST_DENIED_VALUES_ORG_POLICY_VIOLATION":
          self = .remediationListDeniedValuesOrgPolicyViolation
        case "REMEDIATION_RESTRICT_CMEK_CRYPTO_KEY_PROJECTS_ORG_POLICY_VIOLATION":
          self = .remediationRestrictCmekCryptoKeyProjectsOrgPolicyViolation
        case "REMEDIATION_RESOURCE_VIOLATION": self = .remediationResourceViolation
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RemediationType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .remediationBooleanOrgPolicyViolation
        case 2: self = .remediationListAllowedValuesOrgPolicyViolation
        case 3: self = .remediationListDeniedValuesOrgPolicyViolation
        case 4: self = .remediationRestrictCmekCryptoKeyProjectsOrgPolicyViolation
        case 5: self = .remediationResourceViolation
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("REMEDIATION_TYPE_UNSPECIFIED")
        case .remediationBooleanOrgPolicyViolation:
          return try container.encode("REMEDIATION_BOOLEAN_ORG_POLICY_VIOLATION")
        case .remediationListAllowedValuesOrgPolicyViolation:
          return try container.encode("REMEDIATION_LIST_ALLOWED_VALUES_ORG_POLICY_VIOLATION")
        case .remediationListDeniedValuesOrgPolicyViolation:
          return try container.encode("REMEDIATION_LIST_DENIED_VALUES_ORG_POLICY_VIOLATION")
        case .remediationRestrictCmekCryptoKeyProjectsOrgPolicyViolation:
          return try container.encode(
            "REMEDIATION_RESTRICT_CMEK_CRYPTO_KEY_PROJECTS_ORG_POLICY_VIOLATION")
        case .remediationResourceViolation:
          return try container.encode("REMEDIATION_RESOURCE_VIOLATION")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.cloudcontrolspartner.v1.Violation.Remediation"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Violation State Values
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified state.
    case unspecified
    /// Violation is resolved.
    case resolved
    /// Violation is Unresolved
    case unresolved
    /// Violation is Exception
    case exception
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .resolved: return 1
      case .unresolved: return 2
      case .exception: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .resolved: return "RESOLVED"
      case .unresolved: return "UNRESOLVED"
      case .exception: return "EXCEPTION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "RESOLVED": self = .resolved
      case "UNRESOLVED": self = .unresolved
      case "EXCEPTION": self = .exception
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .resolved
      case 2: self = .unresolved
      case 3: self = .exception
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .resolved: return try container.encode("RESOLVED")
      case .unresolved: return try container.encode("UNRESOLVED")
      case .exception: return try container.encode("EXCEPTION")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudcontrolspartner.v1.Violation"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
