// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Details of resource Violation
public struct Violation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. Format:
  /// `organizations/{organization}/locations/{location}/customers/{customer}/workloads/{workload}/violations/{violation}`
  public var name: Swift.String = Swift.String()

  /// Output only. Description for the Violation.
  /// e.g. OrgPolicy gcp.resourceLocations has non compliant value.
  public var description: Swift.String = Swift.String()

  /// Output only. Time of the event which triggered the Violation.
  public var beginTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The last time when the Violation record was updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Time of the event which fixed the Violation.
  /// If the violation is ACTIVE this will be empty.
  public var resolveTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Category under which this violation is mapped.
  /// e.g. Location, Service Usage, Access, Encryption, etc.
  public var category: Swift.String = Swift.String()

  /// Output only. State of the violation
  public var state: Violation.State = Violation.State()

  /// Output only. Immutable. Name of the OrgPolicy which was modified with
  /// non-compliant change and resulted this violation. Format:
  ///  `projects/{project_number}/policies/{constraint_name}`
  ///  `folders/{folder_id}/policies/{constraint_name}`
  ///  `organizations/{organization_id}/policies/{constraint_name}`
  public var nonCompliantOrgPolicy: Swift.String = Swift.String()

  /// The folder_id of the violation
  public var folderId: Swift.Int64 = Swift.Int64()

  /// Output only. Compliance violation remediation
  public var remediation: Violation.Remediation? = nil

  /// Initialize a new instance of `Violation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Violation().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Represents remediation guidance to resolve compliance violation for
  /// AssuredWorkload
  public struct Remediation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. Remediation instructions to resolve violations
    public var instructions: Violation.Remediation.Instructions? = nil

    /// Values that can resolve the violation
    /// For example: for list org policy violations, this will either be the list
    /// of allowed or denied values
    public var compliantValues: [Swift.String] = []

    /// Output only. Remediation type based on the type of org policy values
    /// violated
    public var remediationType: Violation.Remediation.RemediationType = Violation.Remediation
      .RemediationType()

    /// Initialize a new instance of `Remediation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Remediation().with { $0.instructions = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Instructions to remediate violation
    public struct Instructions: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Remediation instructions to resolve violation via gcloud cli
      public var gcloudInstructions: Violation.Remediation.Instructions.Gcloud? = nil

      /// Remediation instructions to resolve violation via cloud console
      public var consoleInstructions: Violation.Remediation.Instructions.Console? = nil

      /// Initialize a new instance of `Instructions`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Instructions().with { $0.gcloudInstructions = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      /// Remediation instructions to resolve violation via gcloud cli
      public struct Gcloud: Codable, Equatable, GoogleCloudWkt._AnyPackable,
        Sendable
      {
        /// Gcloud command to resolve violation
        public var gcloudCommands: [Swift.String] = []

        /// Steps to resolve violation via gcloud cli
        public var steps: [Swift.String] = []

        /// Additional urls for more information about steps
        public var additionalLinks: [Swift.String] = []

        /// Initialize a new instance of `Gcloud`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = Gcloud().with { $0.gcloudCommands = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.cloudcontrolspartner.v1.Violation.Remediation.Instructions.Gcloud"
        }
        public init(fromAny any: GoogleCloudWkt.`Any`) throws {
          self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWkt.Struct {
          return try GoogleCloudWkt._slowAnySerialize(message: self)
        }
      }

      /// Remediation instructions to resolve violation via cloud console
      public struct Console: Codable, Equatable, GoogleCloudWkt._AnyPackable,
        Sendable
      {
        /// Link to console page where violations can be resolved
        public var consoleUris: [Swift.String] = []

        /// Steps to resolve violation via cloud console
        public var steps: [Swift.String] = []

        /// Additional urls for more information about steps
        public var additionalLinks: [Swift.String] = []

        /// Initialize a new instance of `Console`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = Console().with { $0.consoleUris = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.cloudcontrolspartner.v1.Violation.Remediation.Instructions.Console"
        }
        public init(fromAny any: GoogleCloudWkt.`Any`) throws {
          self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWkt.Struct {
          return try GoogleCloudWkt._slowAnySerialize(message: self)
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.cloudcontrolspartner.v1.Violation.Remediation.Instructions"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Classifying remediation into various types based on the kind of
    /// violation. For example, violations caused due to changes in boolean org
    /// policy requires different remediation instructions compared to violation
    /// caused due to changes in allowed values of list org policy.
    public enum RemediationType: Codable, Equatable, Sendable {
      /// Unspecified remediation type
      case unspecified
      /// Remediation type for boolean org policy
      case remediationBooleanOrgPolicyViolation
      /// Remediation type for list org policy which have allowed values in the
      /// monitoring rule
      case remediationListAllowedValuesOrgPolicyViolation
      /// Remediation type for list org policy which have denied values in the
      /// monitoring rule
      case remediationListDeniedValuesOrgPolicyViolation
      /// Remediation type for gcp.restrictCmekCryptoKeyProjects
      case remediationRestrictCmekCryptoKeyProjectsOrgPolicyViolation
      /// Remediation type for resource violation.
      case remediationResourceViolation
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .remediationBooleanOrgPolicyViolation: return 1
        case .remediationListAllowedValuesOrgPolicyViolation: return 2
        case .remediationListDeniedValuesOrgPolicyViolation: return 3
        case .remediationRestrictCmekCryptoKeyProjectsOrgPolicyViolation: return 4
        case .remediationResourceViolation: return 5
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "REMEDIATION_TYPE_UNSPECIFIED"
        case .remediationBooleanOrgPolicyViolation:
          return "REMEDIATION_BOOLEAN_ORG_POLICY_VIOLATION"
        case .remediationListAllowedValuesOrgPolicyViolation:
          return "REMEDIATION_LIST_ALLOWED_VALUES_ORG_POLICY_VIOLATION"
        case .remediationListDeniedValuesOrgPolicyViolation:
          return "REMEDIATION_LIST_DENIED_VALUES_ORG_POLICY_VIOLATION"
        case .remediationRestrictCmekCryptoKeyProjectsOrgPolicyViolation:
          return "REMEDIATION_RESTRICT_CMEK_CRYPTO_KEY_PROJECTS_ORG_POLICY_VIOLATION"
        case .remediationResourceViolation: return "REMEDIATION_RESOURCE_VIOLATION"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RemediationType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "REMEDIATION_TYPE_UNSPECIFIED": self = .unspecified
        case "REMEDIATION_BOOLEAN_ORG_POLICY_VIOLATION":
          self = .remediationBooleanOrgPolicyViolation
        case "REMEDIATION_LIST_ALLOWED_VALUES_ORG_POLICY_VIOLATION":
          self = .remediationListAllowedValuesOrgPolicyViolation
        case "REMEDIATION_LIST_DENIED_VALUES_ORG_POLICY_VIOLATION":
          self = .remediationListDeniedValuesOrgPolicyViolation
        case "REMEDIATION_RESTRICT_CMEK_CRYPTO_KEY_PROJECTS_ORG_POLICY_VIOLATION":
          self = .remediationRestrictCmekCryptoKeyProjectsOrgPolicyViolation
        case "REMEDIATION_RESOURCE_VIOLATION": self = .remediationResourceViolation
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RemediationType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .remediationBooleanOrgPolicyViolation
        case 2: self = .remediationListAllowedValuesOrgPolicyViolation
        case 3: self = .remediationListDeniedValuesOrgPolicyViolation
        case 4: self = .remediationRestrictCmekCryptoKeyProjectsOrgPolicyViolation
        case 5: self = .remediationResourceViolation
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .remediationBooleanOrgPolicyViolation: return try container.encode(1)
        case .remediationListAllowedValuesOrgPolicyViolation: return try container.encode(2)
        case .remediationListDeniedValuesOrgPolicyViolation: return try container.encode(3)
        case .remediationRestrictCmekCryptoKeyProjectsOrgPolicyViolation:
          return try container.encode(4)
        case .remediationResourceViolation: return try container.encode(5)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.cloudcontrolspartner.v1.Violation.Remediation"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Violation State Values
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified state.
    case unspecified
    /// Violation is resolved.
    case resolved
    /// Violation is Unresolved
    case unresolved
    /// Violation is Exception
    case exception
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .resolved: return 1
      case .unresolved: return 2
      case .exception: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .resolved: return "RESOLVED"
      case .unresolved: return "UNRESOLVED"
      case .exception: return "EXCEPTION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "RESOLVED": self = .resolved
      case "UNRESOLVED": self = .unresolved
      case "EXCEPTION": self = .exception
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .resolved
      case 2: self = .unresolved
      case 3: self = .exception
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .resolved: return try container.encode(1)
      case .unresolved: return try container.encode(2)
      case .exception: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudcontrolspartner.v1.Violation"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
