// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Contains metadata around the [Workload
/// resource](https://cloud.google.com/assured-workloads/docs/reference/rest/Shared.Types/Workload)
/// in the Assured Workloads API.
public struct Workload: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. Format:
  /// `organizations/{organization}/locations/{location}/customers/{customer}/workloads/{workload}`
  public var name: Swift.String = Swift.String()

  /// Output only. Folder id this workload is associated with
  public var folderId: Swift.Int64 = Swift.Int64()

  /// Output only. Time the resource was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The name of container folder of the assured workload
  public var folder: Swift.String = Swift.String()

  /// Container for workload onboarding steps.
  public var workloadOnboardingState: WorkloadOnboardingState? = nil

  /// Indicates whether a workload is fully onboarded.
  public var isOnboarded: Swift.Bool = Swift.Bool()

  /// The project id of the key management project for the workload
  public var keyManagementProjectId: Swift.String = Swift.String()

  /// The Google Cloud location of the workload
  public var location: Swift.String = Swift.String()

  /// Partner associated with this workload.
  public var partner: Workload.Partner = Workload.Partner()

  /// Initialize a new instance of `Workload`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Workload().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Supported Assured Workloads Partners.
  public enum Partner: Codable, Equatable, Sendable {
    /// Unknown Partner.
    case unspecified
    /// Enum representing S3NS (Thales) partner.
    case localControlsByS3Ns
    /// Enum representing T_SYSTEM (TSI) partner.
    case sovereignControlsByTSystems
    /// Enum representing SIA_MINSAIT (Indra) partner.
    case sovereignControlsBySiaMinsait
    /// Enum representing PSN (TIM) partner.
    case sovereignControlsByPsn
    /// Enum representing CNTXT (Kingdom of Saudi Arabia) partner.
    case sovereignControlsByCntxt
    /// Enum representing CNXT (Kingdom of Saudi Arabia) partner offering without
    /// EKM provisioning.
    case sovereignControlsByCntxtNoEkm
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .localControlsByS3Ns: return 1
      case .sovereignControlsByTSystems: return 2
      case .sovereignControlsBySiaMinsait: return 3
      case .sovereignControlsByPsn: return 4
      case .sovereignControlsByCntxt: return 6
      case .sovereignControlsByCntxtNoEkm: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PARTNER_UNSPECIFIED"
      case .localControlsByS3Ns: return "PARTNER_LOCAL_CONTROLS_BY_S3NS"
      case .sovereignControlsByTSystems: return "PARTNER_SOVEREIGN_CONTROLS_BY_T_SYSTEMS"
      case .sovereignControlsBySiaMinsait: return "PARTNER_SOVEREIGN_CONTROLS_BY_SIA_MINSAIT"
      case .sovereignControlsByPsn: return "PARTNER_SOVEREIGN_CONTROLS_BY_PSN"
      case .sovereignControlsByCntxt: return "PARTNER_SOVEREIGN_CONTROLS_BY_CNTXT"
      case .sovereignControlsByCntxtNoEkm: return "PARTNER_SOVEREIGN_CONTROLS_BY_CNTXT_NO_EKM"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Partner/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PARTNER_UNSPECIFIED": self = .unspecified
      case "PARTNER_LOCAL_CONTROLS_BY_S3NS": self = .localControlsByS3Ns
      case "PARTNER_SOVEREIGN_CONTROLS_BY_T_SYSTEMS": self = .sovereignControlsByTSystems
      case "PARTNER_SOVEREIGN_CONTROLS_BY_SIA_MINSAIT": self = .sovereignControlsBySiaMinsait
      case "PARTNER_SOVEREIGN_CONTROLS_BY_PSN": self = .sovereignControlsByPsn
      case "PARTNER_SOVEREIGN_CONTROLS_BY_CNTXT": self = .sovereignControlsByCntxt
      case "PARTNER_SOVEREIGN_CONTROLS_BY_CNTXT_NO_EKM": self = .sovereignControlsByCntxtNoEkm
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Partner/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .localControlsByS3Ns
      case 2: self = .sovereignControlsByTSystems
      case 3: self = .sovereignControlsBySiaMinsait
      case 4: self = .sovereignControlsByPsn
      case 6: self = .sovereignControlsByCntxt
      case 7: self = .sovereignControlsByCntxtNoEkm
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .localControlsByS3Ns: return try container.encode(1)
      case .sovereignControlsByTSystems: return try container.encode(2)
      case .sovereignControlsBySiaMinsait: return try container.encode(3)
      case .sovereignControlsByPsn: return try container.encode(4)
      case .sovereignControlsByCntxt: return try container.encode(6)
      case .sovereignControlsByCntxtNoEkm: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudcontrolspartner.v1.Workload"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
