// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Container for workload onboarding information.
public struct WorkloadOnboardingStep: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The onboarding step.
  public var step: WorkloadOnboardingStep.Step = WorkloadOnboardingStep.Step()

  /// The starting time of the onboarding step.
  public var startTime: GoogleWKT.Timestamp? = nil

  /// The completion time of the onboarding step.
  public var completionTime: GoogleWKT.Timestamp? = nil

  /// Output only. The completion state of the onboarding step.
  public var completionState: CompletionState = CompletionState()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `WorkloadOnboardingStep`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = WorkloadOnboardingStep().with { $0.step = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let step = CodingKeys(stringValue: "step")
    static let startTime = CodingKeys(stringValue: "startTime")
    static let completionTime = CodingKeys(stringValue: "completionTime")
    static let completionState = CodingKeys(stringValue: "completionState")

    static let _knownKeys: Set<Swift.String> = [
      "step",
      "startTime",
      "completionTime",
      "completionState",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(WorkloadOnboardingStep.Step.self, forKey: .step) {
      self.step = value
    }
    self.startTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .startTime)
    self.completionTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .completionTime)
    if let value = try container.decodeIfPresent(CompletionState.self, forKey: .completionState) {
      self.completionState = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.step, forKey: .step)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encodeIfPresent(self.completionTime, forKey: .completionTime)
    try container.encode(self.completionState, forKey: .completionState)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Enum for possible onboarding steps.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Step: Codable, Equatable, Sendable {
    /// Unspecified step.
    case unspecified
    /// EKM Provisioned step.
    case ekmProvisioned
    /// Signed Access Approval step.
    case signedAccessApprovalConfigured
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .ekmProvisioned: return 1
      case .signedAccessApprovalConfigured: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STEP_UNSPECIFIED"
      case .ekmProvisioned: return "EKM_PROVISIONED"
      case .signedAccessApprovalConfigured: return "SIGNED_ACCESS_APPROVAL_CONFIGURED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Step/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STEP_UNSPECIFIED": self = .unspecified
      case "EKM_PROVISIONED": self = .ekmProvisioned
      case "SIGNED_ACCESS_APPROVAL_CONFIGURED": self = .signedAccessApprovalConfigured
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Step/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .ekmProvisioned
      case 2: self = .signedAccessApprovalConfigured
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STEP_UNSPECIFIED")
      case .ekmProvisioned: return try container.encode("EKM_PROVISIONED")
      case .signedAccessApprovalConfigured:
        return try container.encode("SIGNED_ACCESS_APPROVAL_CONFIGURED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudcontrolspartner.v1.WorkloadOnboardingStep"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
